# Local development - builds from source with debug enabled
services:
  shelfmark-dev:
    extends:
      file: ./compose/docker-compose.yml
      service: shelfmark
    build:
      context: .
      dockerfile: Dockerfile
      target: shelfmark
    cap_add:
      - SYS_PTRACE
    environment:
      DEBUG: true
      # HIDE_LOCAL_AUTH: true
      OIDC_AUTO_REDIRECT: true
    volumes:
      - ./.local/config:/config
      - ./.local/books:/books
      - ./.local/log:/var/log/shelfmark
      - ./.local/tmp:/tmp/shelfmark
      - ./shelfmark:/app/shelfmark:ro
      # Required for torrent / usenet - path must match your download client's volume exactly
      # - /path/to/downloads:/path/to/downloads
